$(document).ready(function(){
    $('.labs').hide();
    $('.content').hide();  
    //lab1 
    $('#lab1').click(function(){
        $('.labs').hide();  
        $('.lab1').show();      
    });
    $('#DescriptionOfTheSubjectEnvironmentLab1').click(function(){
        $('.content').hide();  
        $('.DescriptionOfTheSubjectEnvironmentLab1').show();      
    });
    $('#ThemeMetaLab1').click(function(){
        $('.content').hide();  
        $('.ThemeMetaLab1').show();      
    });
    $('#ConclusionsLab1').click(function(){
        $('.content').hide();  
        $('.ConclusionsLab1').show();      
    });
    $('#TABLESLab1').click(function(){
        $('.content').hide();  
        $('.TABLESLab1').show();      
    });
    $('#FORMSLab1').click(function(){
        $('.content').hide();  
        $('.FORMSLab1').show();      
    });
    $('#IMAGELab1').click(function(){
        $('.content').hide();  
        $('.IMAGELab1').show();      
    });
    $('#LISTLab1').click(function(){
        $('.content').hide();  
        $('.LISTLab1').show();      
    });
    $('#LINKLab1').click(function(){
        $('.content').hide();  
        $('.LINKLab1').show();      
    });
        //lab2 
        $('#lab2').click(function(){
            $('.labs').hide();  
            $('.lab2').show();      
        });
        $('#LISTSLab2').click(function(){
            $('.content').hide();  
            $('.LISTSLab2').show();      
        });
        $('#IDENTIFIERSLab2').click(function(){
            $('.content').hide();  
            $('.IDENTIFIERSLab2').show();      
        });
        $('#DEVIATIONSLab2').click(function(){
            $('.content').hide();  
            $('.DEVIATIONSLab2').show();      
        });
        $('#FloatingElementsLab2').click(function(){
            $('.content').hide();  
            $('.FloatingElementsLab2').show();      
        });
        $('#CONCLUSIONSLab2').click(function(){
            $('.content').hide();  
            $('.CONCLUSIONSLab2').show();      
        });
        $('#StatementOfTheLabLab2').click(function(){
            $('.content').hide();  
            $('.StatementOfTheLabLab2').show();      
        });
        $('#TagAndClassSelectorsLab2').click(function(){
            $('.content').hide();  
            $('.TagAndClassSelectorsLab2').show();      
        });
        $('#PseudoclassesAndPseudoelementsLab2').click(function(){
            $('.content').hide();  
            $('.PseudoclassesAndPseudoelementsLab2').show();      
        });
        $('#GroupingOfSelectorsLab2').click(function(){
            $('.content').hide();  
            $('.GroupingOfSelectorsLab2').show();      
        });
});