$(document).ready(function(){
    $('.labs').hide();
    $('.content').hide();  
    //lab1 
    $('#lab1').click(function(){
        $('.labs').hide();  
        $('.lab1').show();      
    });
    $('#DescriptionOfTheSubjectEnvironment').click(function(){
        $('.content').hide();  
        $('.DescriptionOfTheSubjectEnvironment').show();      
    });
    $('#ThemeMeta').click(function(){
        $('.content').hide();  
        $('.ThemeMeta').show();      
    });
    $('#Conclusions').click(function(){
        $('.content').hide();  
        $('.Conclusions').show();      
    });
    $('#TABLES').click(function(){
        $('.content').hide();  
        $('.TABLES').show();      
    });
    $('#FORMS').click(function(){
        $('.content').hide();  
        $('.FORMS').show();      
    });
    $('#IMAGE').click(function(){
        $('.content').hide();  
        $('.IMAGE').show();      
    });
    $('#LIST').click(function(){
        $('.content').hide();  
        $('.LIST').show();      
    });
    $('#LINK').click(function(){
        $('.content').hide();  
        $('.LINK').show();      
    });
});